# Configuration for Adaptive Token Bayesian Flow Network experiments

# General Settings
experiment_name: "atbfn_experiment"
random_seed: 42
device: "cuda"  # or cpu

# Data settings
dataset: "cifar10"
data_dir: "./data"
batch_size: 32
num_workers: 4
image_resolutions: [32, 64, 128]  # Multiple resolutions for testing

# Model settings
# Tokenizer
token_dim: 64
in_channels: 3

# SDE Evolution
base_dt: 0.1
num_evolution_steps: 5
use_adaptive_sde: true
use_attention: true

# Training
num_epochs: 10
learning_rate: 0.001
weight_decay: 0.0001

# Testing/Quick test
quick_test: true
quick_test_batch_size: 8
quick_test_iterations: 3
