
seed: 42
output_dir: ./logs
run_tests: true

dataset:
  name: VOC
  max_samples: 50  # Reduce for faster execution
  data_dir: ./data

model:
  feature_extractor: resnet18
  pretrained: true

experiments:
  run_experiment1: true
  run_experiment2: true
  run_experiment3: true
  
  experiment1:
    max_samples: 20
    save_plot: true
    
  experiment2:
    max_samples: 20
    save_plot: true
    
  experiment3:
    max_samples: 5
    save_plot: true
