# GSD Model Configuration
model:
  name: "geometric_score_distillation"
  latent_dim: 128
  image_size: 256
  channels: 3
  
# Training parameters
training:
  batch_size: 8
  epochs: 100
  learning_rate: 0.0001
  lambda_iso: 1.0  # Weight for isometry loss
  lambda_score: 1.0  # Weight for score identity loss
  test_run: true  # Flag for quick test runs
  
# Evaluation parameters
evaluation:
  num_samples: 64
  batch_size: 8
  
# Dataset parameters
dataset:
  name: "celeba_hq"
  path: "/data/dataset/celeba_hq/images"
  validation_split: 0.1
