# Configuration for MCAD experiments

# General settings
experiment_name: "MCAD"
seed: 42
device: "cuda"  # Use "cpu" for non-GPU environments

# Dataset settings
dataset:
  name: "CIFAR10"  # Dataset to use
  data_dir: "./data"
  batch_size: 64
  test_batch_size: 100

# Model settings
model:
  base_channels: 32
  use_momentum: true
  adaptive_consistency: true

# Training settings
training:
  epochs: 10
  lr: 0.001
  noise_std: 0.1
  momentum_beta: 0.9

# Experiment settings
experiments:
  convergence:
    enabled: true
    epochs: 5
  robustness:
    enabled: true
    data_percentages: [0.1, 0.3, 0.5]
    noise_levels: [0.05, 0.1, 0.2]
    seeds: 3
  ablation:
    enabled: true
    variants:
      - {name: "no_momentum", use_momentum: false, adaptive_consistency: true}
      - {name: "fixed_consistency", use_momentum: true, adaptive_consistency: false}
      - {name: "full_mcad", use_momentum: true, adaptive_consistency: true}

# Test run settings (for quick verification)
test_run:
  enabled: true
  epochs: 1
  max_batches: 5
