model:
  input_dim: 768
  batch_size: 32
  seq_len: 10
  learning_rate: 0.001
  epochs: 50

training:
  optimizer: adam
  weight_decay: 0.01
  early_stopping_patience: 5

data:
  train_split: 0.8
  val_split: 0.1
