import torch
import numpy as np
import matplotlib.pyplot as plt
from skimage.metrics import structural_similarity as ssim_metric
from skimage.metrics import peak_signal_noise_ratio as psnr_metric

def diffusion_process(image, acsc_enabled=True):
    """
    Simulate a diffusion process on the input image.
    Uses a dummy (iterative) process that applies brightness corrections.
    
    Args:
      image: PyTorch tensor of shape [1, 1, H, W] (normalized 0-1).
      acsc_enabled: Boolean flag; if True use dynamic (adaptive) correction.
    
    Returns:
      output: Processed image tensor.
    """
    t_steps = torch.linspace(0, 1, steps=10)
    output = image.clone()
    for i, t in enumerate(t_steps):
        if acsc_enabled:
            factor = 1.0 - (abs(0.5 - t.item())*2)  # scales from 0 at endpoints to 1 at midpoint
        else:
            factor = 0.8
        output = output * factor
    return output

def compute_brightness(image_region):
    """
    Compute brightness as the mean intensity.
    Works on NumPy arrays.
    """
    return np.mean(image_region)

def evaluate_image_quality(original, generated):
    """
    Compute brightness error (MAE on border regions) as well as SSIM and PSNR.
    
    Args:
      original: Torch tensor (1,1,H,W) normalized image.
      generated: Torch tensor (1,1,H,W) generated by diffusion process.
    
    Returns:
      brightness_error, image_ssim, image_psnr
    """
    original_np = original.detach().cpu().numpy().squeeze()
    generated_np = generated.detach().cpu().numpy().squeeze()
    h, w = generated_np.shape
    border = int(0.1 * h)
    
    borders = [generated_np[:border, :],
               generated_np[-border:, :],
               generated_np[:, :border],
               generated_np[:, -border:]]
    
    mae_list = []
    for region in borders:
        mae_list.append(np.abs(compute_brightness(region) - compute_brightness(original_np)))
    brightness_error = np.mean(mae_list)
    
    image_ssim = ssim_metric(original_np, generated_np)
    image_psnr = psnr_metric(original_np, generated_np)
    
    return brightness_error, image_ssim, image_psnr
    
def diffusion_full_acsc(image):
    """
    Simulate diffusion process using adaptive caching (ACSC).
    Returns processed image and measured runtime.
    """
    import time
    start = time.time()
    output = image.clone()
    cached_feature = None
    for step in range(10):
        if cached_feature is None:
            cached_feature = output * 0.95
        output = output * (1.0 - 0.05 * step) + cached_feature * 0.05
    end = time.time()
    return output, (end - start)

def diffusion_baseline(image):
    """
    Simulate diffusion process without caching (baseline recomputation each step).
    Returns processed image and measured runtime.
    """
    import time
    start = time.time()
    output = image.clone()
    for step in range(10):
        computed_feature = output * 0.95  # full recomputation
        output = output * (1.0 - 0.05 * step) + computed_feature * 0.05
    end = time.time()
    return output, (end - start)

def diffusion_process_variant(image, use_caching=True, adaptive_blending=True):
    """
    Simulate the diffusion process for different configurations.
    
    Args:
      image: input torch tensor.
      use_caching: If True, use caching of computed features.
      adaptive_blending: If True, use dynamic (adaptive) blending; otherwise, use fixed correction.
    
    Returns:
      output: Processed image tensor.
    """
    output = image.clone()
    cached_feature = None if use_caching else None
    for step in range(10):
        if use_caching:
            if cached_feature is None:
                cached_feature = output * 0.95  # simulate feature extraction
            feature = cached_feature
        else:
            feature = output * 0.95  # recompute every step

        if adaptive_blending:
            blending_factor = 1.0 - abs(0.5 - (step / 10)) * 2  # from 0 at center to 1 at endpoints
            blending_factor = np.clip(blending_factor, 0, 1)
        else:
            blending_factor = 0.8  # fixed value

        output = output * (1.0 - blending_factor) + feature * blending_factor
    return output

def save_figure(fig, filename, directory="logs"):
    """
    Save a figure as a high-quality PDF.
    
    Args:
      fig: matplotlib figure object
      filename: output filename (without extension)
      directory: output directory
    """
    import os
    os.makedirs(directory, exist_ok=True)
    pdf_path = os.path.join(directory, f"{filename}.pdf")
    fig.savefig(pdf_path, format='pdf', bbox_inches='tight', dpi=300)
    print(f"Figure saved to {pdf_path}")
    return pdf_path
