"""
Utility functions for generating synthetic data for the NSRPP experiments.
"""

import numpy as np
import torch

def generate_synthetic_data(theta, n_samples=1000):
    """
    Generate synthetic data from a mixture of two Gaussians.
    The means are a non-linear function of theta.
    
    Args:
        theta (float): Parameter controlling the data distribution
        n_samples (int): Number of samples to generate
    
    Returns:
        numpy.ndarray: Generated data samples
    """
    mu1 = np.sin(theta) * 5.0
    mu2 = np.cos(theta) * 5.0
    sigma = 1.0
    pis = [0.5, 0.5]
    samples = []
    for _ in range(n_samples):
        if np.random.rand() < pis[0]:
            sample = np.random.normal(mu1, sigma)
        else:
            sample = np.random.normal(mu2, sigma)
        samples.append(sample)
    return np.array(samples)

def estimate_risk(theta, n_samples=500):
    """
    Estimate the risk as the mean squared error between synthetic data
    (generated by theta-dependent distribution) and theta.
    
    Args:
        theta (float): Parameter controlling the data distribution
        n_samples (int): Number of samples to use for risk estimation
    
    Returns:
        float: Estimated risk value
    """
    data_samples = generate_synthetic_data(theta, n_samples=n_samples)
    risk = np.mean((data_samples - theta)**2)
    return risk

def create_dataset(n_samples=1000):
    """
    Create synthetic dataset of (theta, risk) pairs.
    Theta values are sampled uniformly from [-pi, pi].
    
    Args:
        n_samples (int): Number of samples to generate
    
    Returns:
        tuple: (thetas, risks) arrays
    """
    thetas = np.random.uniform(-np.pi, np.pi, size=(n_samples, 1))
    risks = np.array([estimate_risk(theta.item()) for theta in thetas])
    return thetas, risks
